version: '3'

services:
  app:
    build:
      context: ./containers/app
    working_dir: /java_app_sample
    depends_on:
      - db
      - gradle
    volumes:
      - ./build/libs/:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"

  db:
    build:
      context: ./containers/db
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3307"

  gradle:
    build:
      context: ./containers/gradle
    working_dir: /java_app_sample
    volumes:
      - ./:/java_app_sample
    command: gradle -t build --warning-mode all

volumes:
  mysql: {}
